#
# phdtex travis CI configuration
# inspired by https://github.com/harshjv/travis-ci-latex-pdf
#
# Copyright (c) 2017, Andrew Kanner <andrew.kanner@gmail.com>.
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
sudo: required
dist: trusty
services:
- docker
before_install:
# 1. texlive-current: this is too expensive
#- wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
#- tar xzf install-tl-unx.tar.gz
#- cd install-tl-*
#- export TEXMFHOME=~/.texlive$(date +'%F') && export TEXDIR=/usr/local/texlive/$(date +'%F') && echo i | sudo ./install-tl
#
# 2. trusty-native: some problems with texlive-2013 (pgfplots is too old)
#- sudo apt-get -qq update
#- sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng
#- sudo apt-get install -y --no-install-recommends texlive-lang-cyrillic latex-xcolor texlive-pictures pgf
#
# 3. trusty-upgrade: upgrade fails
#- sudo apt-get -qq update && sudo apt-get -qy dist-upgrade
#- sudo apt-get install -qy --no-install-recommends texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra dvipng
#- sudo apt-get install -qy --no-install-recommends texlive-lang-cyrillic latex-xcolor texlive-pictures pgf
#- sudo apt-get -q clean
#
# 4. docker: this is too expensive
#- docker pull gentoo/stage3-amd64
#- docker create -v /usr/portage --name myportagesnapshot gentoo/portage:latest /bin/true
##- docker run -d -p 127.0.0.1:80:4567 gentoo/stage3-amd64 /bin/sh -c "echo \"=dev-tex/pscyr-0.4d_beta9 ~amd64\" >> /etc/portage/package.accept_keywords && emerge texlive texlive-core texlive-latexextra texlive-pstricks texlive-langcyrillic texlive-bibtexextra pscyr make"
#- docker run --volumes-from myportagesnapshot gentoo/stage3-amd64:latest /bin/bash -c "echo \"=dev-tex/pscyr-0.4d_beta9 ~amd64\" >> /etc/portage/package.accept_keywords && emerge texlive texlive-core texlive-latexextra texlive-pstricks texlive-langcyrillic texlive-bibtexextra pscyr make"
##- docker ps -a
#
# 5. docker-special: image with gentoo, texlive installed
- docker pull akanner/gentoo-texlive
script:
# 1-3. native build
#- ./externals/pscyr-install.sh
#- make -j5
#
# 4-5. docker build
#- docker run --user="$(id -u):$(id -g)" --net=none -v $(pwd):/src gentoo/stage3-amd64:latest make -C src -j5
- docker run --rm -v $(pwd):/src akanner/gentoo-texlive:latest make -C src -j5
deploy:
  provider: releases
  api_key:
    secure: "r37YwjWK5YUYicCRiJ5N5RKWS0CRkY6YW9IA6/zYOYctR1IdlS+xX7z2Y4R9uVcDA9/qsDF4855mlNWeTzVJyDVUSYnPahUsKOQBE069NLVL3KlG6FReVsSrmY4T1n5V3DMts4X1EEhMFSykSjYM4X3xbzGj/kg8W+1V3ZY7QbTgAywgX5aidT+Jzb/hUIBZCWtxR+SovfGlkxkprDz8PXD6CK+r8zYUmXXsFlRovOblmxVPaiU+Nn82YuKVVC9jTbPl0ICDoBXwWbUM0IbCYb4qL3XR6TZmrKzQLd1GY3i3MmtHpsXKgA7nFWfP8hXsG+AMlc37FqyueFoL3dLbyAjzPEKNmIdaIKKxfw5LZeAOTDAusoBf5Wy1D4qJOcJfQ1KEQvJYNQbjIeFj3btsFaWAk+Elw5BQ2MvHMoZkCABbFX4a3UmClMNlaqvj8jMPUNOmCWkub+j54ycrLPbSnucuFZPnMuMmNNhPyBL9ZqeNCToIcF0jPjoJVX/5ESS+ApooQV1X2OCn7urW9f49CUBHYiBtcYHjkRR2JTsT04R+0mO5Rd6LIZ/iRXwg1JoEbfR/9U0CS3Jd/25j3W1TqmfxQwI4IZMxHJBuk/ajkDkBTMitjypSCmUP/gngi2MDGauFq9Ea/r9NRLGzcaELM0HSTSc7cJ80MvGROmsi2ys="
  file:
    - dissertation.pdf
    - synopsis.pdf
    - booklet.pdf
  skip_cleanup: true
  on:
    repo: kanner/phdtex
    tags: true
#  overwrite: true
